cart/urls.py
from django.urls import path
from . import views

app_name='cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

mitienda/urls.py
from django.urls import path
from . import views

app_name='tienda'

urlpatterns = [
    path('', views.product_list, name='product_list'),
    path('<slug:category_slug>/', views.product_list, name='product_list_category'),
    path('<int:id>/<slug:slug>/', views.product_detail, name='product_detail'),
]

orders/urls.py
from django.urls import path

from . import views

app_name = 'orders'

urlpatterns = [
    # Define your URL patterns here
    path('create/', views.order_create, name='order_create'),
]

p003mitienda/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('', include('mitienda.urls', namespace='mitienda')),

]

# Configuracion para servir archivos multimedia en modo desarrollo
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

#un ejemplo para servir archivos estaticos en modo de produccion seria:
# from django.conf.urls.static import static
# urlpatterns += static('/static/', document_root='/path/to/static/')

mitienda/models.py
from django.db import models
from django.urls import reverse

#modelo para almacenar las categorias de los productos
class Categoria(models.Model):
    name = models.CharField(max_length=200)
    slug=models.SlugField(max_length=200)

    class Meta:
        ordering=['name']
        indexes = [
            models.Index(fields=['name']), #sirve en gestores de bases de datos para mejorar la velocidad de las consultas
        ]

    def __str__(self):
        return self.name
    
    #la funcion get_absolute_url devuelve la URL canónica para un objeto dado
    def get_absolute_url(self):
        return reverse('tienda:product_list_category', args=[self.slug])

#modelo para almacenar los productos
class Producto(models.Model):
    category = models.ForeignKey(Categoria, related_name='products', on_delete=models.CASCADE)
    name= models.CharField(max_length=200)
    slug=models.SlugField(max_length=200)
    image=models.ImageField(upload_to='products/%Y/%m/%d', blank=True)
    description=models.TextField(blank=True)
    price=models.DecimalField(max_digits=5, decimal_places=2)
    available=models.BooleanField(default=True)
    created=models.DateTimeField(auto_now=True)
    updated=models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering=['name']

    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('tienda:product_detail', args=[self.id, self.slug])
    

orders/models.py
from django.db import models
from mitienda.models import Producto

# Create your models here.
class Order(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    email = models.EmailField()
    address = models.CharField(max_length=250)
    postal_code = models.CharField(max_length=10)
    city = models.CharField(max_length=100)
    created = models.DateTimeField(auto_now_add=True)
    paid = models.BooleanField(default=False)

    class Meta:
        ordering = ['-created']
        indexes = [
            models.Index(fields=['-created'])
        ]

    def __str__(self):
        return f'Order {self.id}'
    

class OrderItem(models.Model):
    order = models.ForeignKey(Order, related_name='items', on_delete=models.CASCADE)
    product = models.ForeignKey(Producto, related_name='order_items', on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=5,
                                decimal_places=2)
    quantity = models.PositiveIntegerField(default=1)

    def __str__(self):
        return str(self.id)

orders/forms.py
from django import forms
from .models import Order

class OrderCreateForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ['first_name', 'last_name', 'email', 'address', 'postal_code', 'city']

cart/views.py
from django.shortcuts import get_object_or_404, redirect, render
from django.views.decorators.http import require_POST

from mitienda.models import Producto

from .form import CartAddProductForm
from .cart import Cart

# Create your views here.
@require_POST
def cart_add(request,product_id):
    cart=Cart(request)
    product=get_object_or_404(Producto,id=product_id)
    form=CartAddProductForm(request.POST)
    if form.is_valid():
        cd=form.cleaned_data
        cart.add(product=product,quantity=cd['cantidad'],override_quantity=cd['override'])
        return redirect('cart:cart_detail')
    
@require_POST
def cart_remove(request,product_id):
    cart=Cart(request)
    product=get_object_or_404(Producto,id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')

def cart_detail(request):
    cart=Cart(request)
    """ for item in cart:
        item['update_quantity_form']=CartAddProductForm(initial={'cantidad':item['quantity'],'override':True}) """
    return render(request,'cart/details.html',{'cart':cart})

mitienda/views.py
from django.shortcuts import render,get_object_or_404

from cart.form import CartAddProductForm
from .models import Producto, Categoria

# Create your views here.
def product_list(request, category_slug=None):
    category = None
    categories = Categoria.objects.all()
    products=Producto.objects.filter(available=True) 

    if category_slug:
        category= get_object_or_404(Categoria, slug=category_slug)
        products=products.filter(category=category)
    
    return render(request, 'tienda/products/list.html', {'category': category, 'categories': categories, 'products': products})

def product_detail(request,id,slug):
    product=get_object_or_404(Producto, id=id, slug=slug, available=True)
    cart_product_form= CartAddProductForm()
    return render(request,'tienda/products/detail.html', {'product': product, 'cart_product_form': cart_product_form})

orders/views.py
from django.shortcuts import render

from cart.cart import Cart
from .forms import OrderCreateForm
from .models import OrderItem

def order_create(request):
    cart = Cart(request)
    if request.method == 'POST':
        form = OrderCreateForm(request.POST)
        if form.is_valid():
            order = form.save()
            for item in cart:
                OrderItem.objects.create(order=order,
                                         product = item['product'],
                                         price = item['price'],
                                         quantity = item['quantity'])
            cart.clear()
            return render(request,
                          'orders/created.html',
                          {'order':order})
    else:
        form = OrderCreateForm()
    return render(request, 'orders/create.html', {'form':form, 'cart':cart})

cart/templates/cart/details.html
{% extends "tienda/master.html" %}
{% load static %}
{% block title %}
  Tu carrito
{% endblock %}
{% block content %}
  <div class="container mt-5">
    <h1>Tu carrito</h1>
    <div class="table-responsive">
      <table class="table table-striped">
        <thead>
          <tr>
            <th>Imagen</th>
            <th>Producto</th>
            <th>Cantidad</th>
            <th>Remover</th>
            <th>Precio</th>
            <th>Total</th>
          </tr>
        </thead>
        <tbody>
          {% for item in cart %}
            {% with product=item.product %}
              <tr>
                <td>
                  <a href="{{ product.get_absolute_url }}">
                    <img src="{% if product.image %}{{ product.image.url }}{% else %}{% static 'img/no_image.jpg' %}{% endif %}" class="img-fluid" alt="{{ product.name }}" style="max-width: 100px;">
                  </a>
                </td>
                <td>{{ product.name }}</td>
                <td>{{ item.quantity }}</td>
                <td>
                  <form action="{% url 'cart:cart_remove' product.id %}" method="post">
                    <button type="submit" class="btn btn-danger">Remover</button>
                    {% csrf_token %}
                  </form>
                </td>
                <td>${{ item.price }}</td>
                <td>${{ item.total_price }}</td>
              </tr>
            {% endwith %}
          {% endfor %}
          <tr class="table-secondary">
            <td colspan="5">Total</td>
            <td>${{ cart.get_total_price }}</td>
          </tr>
        </tbody>
      </table>
    </div>
    <div class="text-right mt-3">
      <a href="{% url 'tienda:product_list' %}" class="btn btn-light">Continuar comprando</a>
      <!--<a href="#" class="btn btn-primary">Pagar</a>-->
      <a href="{% url 'orders:order_create' %}" class="btn btn-primary">Pagar</a>
    </div>
  </div>
{% endblock %}

mitienda/templates/tienda/master.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Mi tienda{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-sRIl4kxILFvY47J16cr9ZwB07vP4J8+LH7qKQnuqkuIAvNWLzeN8tE5YBujZqJLB" crossorigin="anonymous">

</head>

<body>

    <nav class="navbar navbar-expand-lg" style="background-color: #575aff;">
        <div class="container-fluid">
            <a class="navbar-brand text-white" href="{% url 'tienda:product_list' %}">Mi tienda</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup"
                aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                <ul class="navbar-nav ms-auto">
                    <li class="nav-item">
                        <a class="nav-link text-white" href="#">Productos</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-white" href="#">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-white" href="#">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-white" href="#">Home</a>
                    </li>
                </ul>
            </div>
    </nav>
    <main>
        <div class="container mt-4">
            <a href="{% url 'cart:cart_detail' %}" class="btn btn-light">
                Carrito 🛒
            </a>
        </div>
        <div class="container">
            <div class="row">
                {% block content %}{% endblock %}

            </div>
        </div>
    </main>
    <footer>{% block footer %}{% endblock %}</footer>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-FKyoEForCGlyvwx9Hj09JcYn3nv7wiPVlz7YYwJrWVcXK/BmnVDxM+D2scQbITxI"
        crossorigin="anonymous"></script>
</body>

</html>

mitienda/templates/tienda/products/detail.html
{% extends "tienda/master.html" %}
{% load static %}
{% block title %}
{{ product.name }}
{% endblock %}
{% block content %}
<div class="container mt-5 mb-5">
  <div class="row">
    <div class="col-md-12 mb-4">
      <a class="text-decoration-none btn btn-primary" href="{% url 'tienda:product_list' %}">Back to Products</a>
    </div>
    <div class="col-md-5">
      <img src="{% if product.image %}{{ product.image.url }}{% else %}{% static 'img/no_image.jpg' %}{% endif %}"
        class="img-fluid" alt="{{ product.name }}" style="max-width: 300px;">
    </div>
    <div class="col-md-6">
      <h1>{{ product.name }}</h1>
      <h2>
        <a href="{{ product.category.get_absolute_url }}">
          {{ product.category }}
        </a>
      </h2>
      <p class="price">${{ product.price }}</p>
      <div class="py-3">
        <form action="{% url 'cart:cart_add' product.id %}" method="post">
          {{ cart_product_form }}
          {% csrf_token %}
          <input type="submit" value="Agregar al carrito">
        </form>
      </div>
      <p>{{ product.description|linebreaks }}</p>
    </div>

  </div>
</div>
{% endblock %}

mitienda/templates/tienda/products/list.html
{% extends "tienda/master.html" %}
{% load static %}
{% block title%}
{% if category %} {{category.name}} {% else %}Productos {% endif %} - Mi tienda
{% endblock %}
 {% block content %}
<div class="col-md-3">
    <h3>Categorias</h3>
    <ul class="list-group">
        <li class="list-group-item {% if not category %}active{% endif %}">
            <a href="{% url 'tienda:product_list' %}" style="color: black;">Todas</a>
        </li>
        {% for cat in categories %}
        <li class="list-group-item {% if category.slug == cat.slug %}active{% endif %}">
            <a href="{{ cat.get_absolute_url }}" style="color:black"> {{ cat.name }} </a>
        </li>
        {% endfor %}
    </ul>
</div>
<div class="col-md-9">
    <h1 class="mb-4">
        {% if category %} {{category.name}} {% else %}Productos {% endif %}
    </h1>
    <div class="row">
        {% for product in products %}
        <div class="col-md-4 mb-4">
            <div class="card">
                <img src="{% if product.image %}{{ product.image.url }}{% else %}{% static 'img/no_image.jpg' %}{% endif %}" class="card-img-top" alt="{{ product.name }}">
                <div class="card-body">
                    <h5 class="card-title">{{ product.name }}</h5>
                    <p class="card-text">$ {{ product.price }}</p>
                    <a href="{{ product.get_absolute_url }}" class="btn btn-primary">Ver detalles</a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{%endblock %}

orders/templates/orders/create.html
{% extends "tienda/master.html" %}
{% block title %}
  Tu orden
{% endblock %}
{% block content %}
  <div class="container mt-5">
    <h1>Pagar</h1>
    <div class="row">
      <div class="col-md-6">
        <div class="order-info">
          <h3>Tu orden</h3>
          <ul class="list-group">
            {% for item in cart %}
              <li class="list-group-item">
                {{ item.quantity }}x {{ item.product.name }}
                <span class="badge bg-primary">${{ item.total_price }}</span>
              </li>
            {% endfor %}
          </ul>
          <p class="mt-3">Total: <strong>${{ cart.get_total_price }}</strong></p>
        </div>
      </div>
      <div class="col-md-6">
        <form method="post" class="order-form">
          <div class="mb-3">
            {% csrf_token %}
            {{ form.as_p }}
          </div>
          <button type="submit" class="btn btn-primary">Pagar</button>
        </form>
      </div>
    </div>
  </div>
{% endblock %}

orders/templates/orders/created.html
{% extends "tienda/master.html" %}
{% block title %}
  Gracias
{% endblock %}
{% block content %}
  <div class="container mt-5">
    <div class="row">
      <div class="col-md-6 offset-md-3">
        <div class="card">
          <div class="card-body">
            <h1 class="card-title text-center">Gracias</h1>
            <p class="card-text text-center">Tu orden se ha completado.</p>
            <p class="card-text text-center">tu número de orden es <strong>{{ order.id }}</strong>.</p>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}